http:
  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend
      entryPoints:
        - web
      priority: 1

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

# Les routes auth et api sont maintenant gérées dynamiquement via Consul Catalog.
# Il ne faut pas les définir ici car l'hôte 'auth-service' n'est pas résolvable sur le PC1.
